config/routes.rb
Rails.application.routes.draw do
  resources :musics, only: [:index]

  resources :artists do
    resources :musics, except: [:index]
  end

  root 'artists#index'
end

app/models/artist.rb
class Artist
  include Neo4j::ActiveNode

  property :name
  property :link
  property :photo

  validates :name, :link, :photo, presence: true

  index :name

  has_many :out, :musics, origin: :artist

end

app/models/music.rb
class Music
  include Neo4j::ActiveNode

  property :title
  property :link

  validates :title, :link, presence: true

  index :title

  has_one :in, :artist, type: :wrote

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  ensure_security_headers # See more: https://github.com/twitter/secureheaders

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @artist.musics.each { |music| music.destroy }
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :link, :photo)
    end

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  before_action :set_artist, only: [:new, :edit, :create, :destroy, :update]

  def index
    @musics = Music.all
  end

  def show
  end

  def new
    @music = Music.new
  end

  def edit
  end

  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        @artist.musics.create(@music, {})

        format.html { redirect_to [@music.artist, @music], notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: [@music.artist, @music] }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to [@music.artist, @music], notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: [@music.artist, @music] }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_music
      @music = Music.find(params[:id])
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def music_params
      params.require(:music).permit(:title, :link)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.slim
- flash.each do |key, value|
  div id="flash_#{key}"
    = value

app/views/artists/_form.html.slim
= simple_form_for(@artist) do |f|

  .form-inputs
    = f.input :name
    = f.input :link
    = f.input :photo

  .form-actions
    = f.button :submit

app/views/artists/edit.html.slim
h1 Editing artist

== render 'form'

= link_to 'Show', @artist
= ' | '
= link_to 'Back', artists_path

app/views/artists/index.html.slim
h1 Listing artists

table
  thead
    tr
      th Name
      th Link
      th Photo
      th
      th
      th
      th

  tbody
    - @artists.each do |artist|
      tr
        td = artist.name
        td = link_to artist.link, artist.link
        td = image_tag artist.photo, width: 100
        td = link_to 'Show', artist
        td = link_to 'Edit', edit_artist_path(artist)
        td = link_to 'Add music', new_artist_music_path(artist)
        td = link_to 'Destroy', artist, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Artist', new_artist_path
= ' | '
= link_to 'All Music', musics_path

app/views/artists/new.html.slim
h1 New artist

== render 'form'

= link_to 'Back', artists_path

app/views/artists/show.html.slim
p
  strong= 'Name: '
  = @artist.name
p
  strong= 'Link: '
  = @artist.link
p
  strong= 'Photo: '
  = image_tag @artist.photo, width: 100
p
  strong= 'Musics: '
  = 'No music found for this artist' if @artist.musics.empty?
  ul
    - @artist.musics.each do |music|
      li
        = link_to music.title, artist_music_path(@artist, music)

= link_to 'New music', new_artist_music_path(@artist)
= ' | '
= link_to 'Edit', edit_artist_path(@artist)
= ' | '
= link_to 'Back', artists_path

app/views/layouts/application.html.slim
doctype 5
html lang="pt"
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="description" content=""

    title
      = page_title(app_name: 'example')

    link href="/favicon.ico" rel=("shortcut icon")
    link rel="author" href="/humans.txt"

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body class=body_class
    = render 'flash_messages'
    = yield

app/views/musics/_form.html.slim
= simple_form_for([@artist, @music]) do |f|

  .form-inputs
    = f.input :title
    = f.input :link

  .form-actions
    = f.button :submit

app/views/musics/edit.html.slim
h1 Editing music

== render 'form'

= link_to 'Show', [@music.artist, @music]
= ' | '
= link_to 'Back', musics_path

app/views/musics/index.html.slim
h1 Listing musics

table
  thead
    tr
      th Title
      th Link
      th Artist
      th
      th
      th

  tbody
    - @musics.each do |music|
      tr
        td = music.title
        td = link_to music.link, music.link
        td = link_to music.artist.name, music.artist
        td = link_to 'Show', artist_music_path(music.artist, music)
        td = link_to 'Edit', edit_artist_music_path(music.artist, music)
        td = link_to 'Destroy', artist_music_path(music.artist, music), data: {:confirm => 'Are you sure?'}, :method => :delete

br

  = link_to 'All Artists', artists_path

app/views/musics/new.html.slim
h1 New music

== render 'form'

= link_to 'Back', musics_path

app/views/musics/show.html.slim
p
  strong= 'Title: '
  = @music.title
p
  strong= 'Link: '
  = link_to @music.link, @music.link
p
  strong= 'Artist: '
  = link_to @music.artist.name, @music.artist

= link_to 'Edit', edit_artist_music_path(@music.artist, @music)
= ' | '
= link_to 'Back', musics_path